version: '3.8'

services:
  php-app:
    build:
      context: ./Docker
    image: my-php-app:latest
    ports:
      - 8010:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
  
    networks:
      - mynet
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet

volumes:
  mariadb_data:

networks:
  mynet:
