version: '3.8'
services:
  school-mvc:
    build:
      context: ./Docker
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - 3307=3306
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: school
      MYSQL_PASSWORD: saboor123
      MYSQL_ROOT_PASSWORD: saboor123
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
      - ./volumes/data/mariadb:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
volumes:
  db-data:
